name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  fluro: ^1.3.4
  json2entity: ^1.0.6
  path_drawing: ^0.4.0
  flutter_screenutil: ^0.4.2
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
  - assets/images/home_icon_homepage_normal.png
  - assets/images/home_icon_homepage_selected.png
  - assets/images/home_icon_mall_normal.png
  - assets/images/home_icon_mall_selected.png
  - assets/images/home_icon_mine_normal.png
  - assets/images/home_icon_mine_selected.png
  - assets/images/home_icon_store_normal.png
  - assets/images/home_icon_store_selected.png
  - assets/images/home_icon_wholesale_normal.png
  - assets/images/home_icon_wholesale_selected.png
  - assets/images/home_banner.png
  - assets/images/home_icon_all.png
  - assets/images/home_icon_collect.png
  - assets/images/home_icon_coupon.png
  - assets/images/home_icon_order.png
  - assets/images/home_icon_presale.png
  - assets/images/home_icon_refund.png
  - assets/images/home_icon_regularpurchase.png
  - assets/images/home_icon_special.png
  - assets/images/bank_zs.png
  - assets/images/home_nav_icon_cart.png
  - assets/images/home_icon_search_small.png
  - assets/images/home_nav_icon_scan.png
  - assets/images/home_images_inform.png

  - assets/images/2.0x/home_icon_homepage_normal.png
  - assets/images/2.0x/home_icon_homepage_selected.png
  - assets/images/2.0x/home_icon_mall_normal.png
  - assets/images/2.0x/home_icon_mall_selected.png
  - assets/images/2.0x/home_icon_mine_normal.png
  - assets/images/2.0x/home_icon_mine_selected.png
  - assets/images/2.0x/home_icon_store_normal.png
  - assets/images/2.0x/home_icon_store_selected.png
  - assets/images/2.0x/home_icon_wholesale_normal.png
  - assets/images/2.0x/home_icon_wholesale_selected.png
  - assets/images/2.0x/home_banner.png
  - assets/images/2.0x/home_icon_all.png
  - assets/images/2.0x/home_icon_collect.png
  - assets/images/2.0x/home_icon_coupon.png
  - assets/images/2.0x/home_icon_order.png
  - assets/images/2.0x/home_icon_presale.png
  - assets/images/2.0x/home_icon_refund.png
  - assets/images/2.0x/home_icon_regularpurchase.png
  - assets/images/2.0x/home_icon_special.png
  - assets/images/2.0x/home_images_inform.png

  - assets/images/3.0x/home_icon_homepage_normal.png
  - assets/images/3.0x/home_icon_homepage_selected.png
  - assets/images/3.0x/home_icon_mall_normal.png
  - assets/images/3.0x/home_icon_mall_selected.png
  - assets/images/3.0x/home_icon_mine_normal.png
  - assets/images/3.0x/home_icon_mine_selected.png
  - assets/images/3.0x/home_icon_store_normal.png
  - assets/images/3.0x/home_icon_store_selected.png
  - assets/images/3.0x/home_icon_wholesale_normal.png
  - assets/images/3.0x/home_icon_wholesale_selected.png
  - assets/images/3.0x/home_banner.png
  - assets/images/3.0x/home_icon_all.png
  - assets/images/3.0x/home_icon_collect.png
  - assets/images/3.0x/home_icon_coupon.png
  - assets/images/3.0x/home_icon_order.png
  - assets/images/3.0x/home_icon_presale.png
  - assets/images/3.0x/home_icon_refund.png
  - assets/images/3.0x/home_icon_regularpurchase.png
  - assets/images/3.0x/home_icon_special.png
  - assets/images/3.0x/home_images_inform.png